version: "2"

services:
  webapp:
   build: ./server
   ports:
    - "3000:3000"
   volumes:
    - ./server:/server
    - /server/node_modules
   links:
    - db
  db:
   image: mongo
   ports:
    - "27017:27017"
   volumes:
    - ./db
